### Consigna 1

a) Si $(I - A)$ es inversible, eso significa que la ecuación $p = (I - A)^{-1}d$ tendrá solución única para **cualquier** valor de $d$. Por lo tanto, la economía puede ajustar la producción $p$ para satisfacer cualquier nivel de demanda $d$.

b) Si $(I - A)$ es inversible y $d=0$, al ser un sistema compatible determinado y homogéneo, la única solución del sistema será $p=0$. Es decir que el la economía estará en equilibrio sin producir nada.


c) Si $(I - A)$ no es inversible entonces no podremos garantizar un valor de $p$ para cada valor de $d$ dado. En algunos casos el sistema podria tener infinitas soluciones o ninguna.

d) Si $(I - A)$ no es inversible y $d=0$, $p=0$ es una solución posible pero no seria la única. Estariamos en el caso de una economía cerrada con dependencia lineal entre los sectores.

### Consigna 2

In [70]:
from funciones import calcularLU, inversaLU
import numpy as np

### Consigna 3

$$\text{Consigna 3:}$$
$$ \text{Resolver el sistema 2 utilizando inversaLU para los siguientes valores de A y d:}$$
$$\begin
{pmatrix}
 0.3&0.0&0.1   \\
 0.05&1.0  &0.2  \\
 0.1& 0.15 &0.1 
\end
{pmatrix}
\text{, d=}
\begin{pmatrix}
 100\\
 100\\
300
\end{pmatrix} $$

In [71]:
I = np.eye(3)
A = np.array([[0.3, 0, 0.1],[0.05, 1, 0.2], [0.1, 0.15, 0.1]])
d = np.array([100, 100, 300])

Calculamos $(I - A)^{-1}$ con las funciones calcularLU e inversaLU y lo encapsulamos en una función para poder reutilizarla despues

In [72]:
def calcularMatrizDeLeontief(A):
    I = np.eye(A.shape[0])
    L, U, P = calcularLU(I - A)
    Leont = inversaLU(L, U, P)
    return Leont

In [73]:
Leont = calcularMatrizDeLeontief(A)

In [74]:
Leont

array([[  1.37931034,  -0.68965517,   0.        ],
       [ -2.98850575, -28.50574713,  -6.66666667],
       [ -0.34482759,  -4.82758621,   0.        ]])

Hallamos p

In [75]:
p = np.matmul(Leont, d)
p

array([   68.96551724, -5149.42528736,  -517.24137931])

$$\text{I. ¿Hay una justificación económica de los valores encontrados para p?}$$
<p>
    Sí, el valor encontrado es:
</p>

$$
\text{p }\approx \begin{pmatrix}
68,965 \\
-5149,425 \\
-517,241
\end{pmatrix}
$$
<p>
    Señalando en la matriz tres sectores S1,S2,S3 hipotéticos de la economía:
</p>
$$
\begin{matrix}
 & S1 &S2  &S3  \\
S1 & 0.3 & 0.0 &0.1  \\
S2 & 0.05 & 1.0 & 0.2 \\
S3 &  0.1& 0.15 & 0.1
\end{matrix}
$$
<p>
    Se ve que el sector S2 necesita comprar insumos (para fabricar una unidad de producto p2) de su mismo sector por un valor igual al total de su producción ($a_{2,2} = 1.0$) y algo más al sector S3 ($a_{2,3} = 0.15$). Con lo cual es un sector deficitario de la economia y no puede satisfacer demanda alguna pues no produce excedente, sólo consume.
Otra forma de verlo es que para fabricar una unidad de producto $p_{2}$ se requiere una unidad de $p_{2}$ entera y algo más de $p_{1}$ y $p_{3}$.
</p>
$$\text{II. ¿Cuál es la característica de la matriz que lleva a esta solución?}$$
<p>
    El coficiente técnico $a_{2,2} = 1.0$ indica que la forma de satisfacer $p = Ap + d$ con $p = (p_{1},p_{2},p_{3})$ seria si $ p_{2} = 0.05*p_{1} + p_{2} + 0.2*p_{3} + 100$ con $p_{1}$, $p_{2}$ y $p_{3}$ no negativos y eso no tiene soluciones positivas.
</p>



### Consigna 4
<p>Analizar analiticamente qué sucede con la producción total cuando a partir de una demanda externa $d$, la demanda externa para el producto 3 cambia en un $\Delta d$. La demanda externa se convierte en:</p>
$$
\text{d' } = d + \begin{pmatrix}
0 \\
0 \\
1
\end{pmatrix}
$$


En general, siendo que $p' = L d' = L(d+\Delta d) = Ld + L\Delta d = p + L\Delta d$, podemos concluir que $p' - p = 
\Delta p = L\Delta d$.

Es decir que para obtener $\Delta p$ tenemos que multiplicar a la matriz de Leontief por $\Delta d$. En este caso
particular, por la forma que tiene $\Delta d$, resulta que $\Delta p = (L_{31}, L_{32}, L_{33})$ siendo $L_{ij}$ el
coeficiente de la matriz de Leontief en la posición $i,j$.

### Consigna 5

Para encontrar la matriz de coeficientes tecnicos utilizamos la siguiente función

In [76]:
def calcularCoeficientesTecnicos(Z, p):
    Pmatrix = np.diag(p)
    L, U, P = calcularLU(Pmatrix)
    Pinversa = inversaLU(L,U,P)
    CoeficientesTecnicos = np.matmul(Z,Pinversa)
    return CoeficientesTecnicos

In [77]:
Z = np.array([[350, 0, 0], [50, 250, 150], [200, 150, 550]])
p = [1000, 500, 1000]
CoeficientesTecnicos = calcularCoeficientesTecnicos(Z, p)

La matriz de coeficientes tecnicos es:

In [78]:
CoeficientesTecnicos

array([[0.35, 0.  , 0.  ],
       [0.05, 0.5 , 0.15],
       [0.2 , 0.3 , 0.55]])

Y la matriz de Leontief asociada a la economia es:

In [79]:
calcularMatrizDeLeontief(CoeficientesTecnicos)

array([[1.53846154, 0.        , 0.        ],
       [0.44871795, 2.5       , 0.83333333],
       [0.98290598, 1.66666667, 2.77777778]])

### Consigna 6

Partiendo de la ecuación (4) que describe el modelo de Leontief para dos regiones $r$ y $s$ y teniendo en cuenta las relaciones intra-regionales e inter-regionales:

$$
\begin{pmatrix}
(I - A^{rr}) & -A^{rs} \\
-A^{sr} & (I - A^{ss})
\end{pmatrix}
\begin{pmatrix}
p^r \\
p^s
\end{pmatrix}
=
\begin{pmatrix}
d^r \\
d^s
\end{pmatrix}
$$


Podemos descomponer la ecuación en el siguiente sistema:

1. Para la región $r$:
   $$
   (I - A^{rr}) p^r - A^{rs} p^s = d^r
   $$

2. Para la región $s$:
   $$
   -A^{sr} p^r + (I - A^{ss}) p^s = d^s
   $$


Despejamos $p_s$ en la segunda ecuacion:
$$
(I - A^{ss}) p^s = A^{sr} p^r + d^s
$$

Multiplicamos ambos lados por la inversa de $ (I - A^{ss}) $ para despejar $p^s$:

$$
p^s = (I - A^{ss})^{-1} A^{sr} p^r + (I - A^{ss})^{-1} d^s
$$


Luego, sustituyendo $p^s$ en la ecuación de $p^r$:

$$
(I - A^{rr}) p^r - A^{rs} \left( (I - A^{ss})^{-1} A^{sr} p^r + (I - A^{ss})^{-1} d^s \right) = d^r
$$

Distribuimos $A^{rs}$:

$$
(I - A^{rr}) p_r - A^{rs} (I - A^{ss})^{-1} A^{sr} p^r - A^{rs} (I - A^{ss})^{-1} d^s = d^r
$$


Sacamos $p^r$ de factor común:

$$
\left( I - A^{rr} - A^{rs} (I - A^{ss})^{-1} A^{sr} \right) p^r = d^r + A^{rs} (I - A^{ss})^{-1} d^s
$$


Finalmente, asumiendo $\Delta d^s = 0$, obtenemos:


$$
\left( I - A^{rr} - A^{rs} (I - A^{ss})^{-1} A^{sr} \right) \Delta p^r = \Delta d^r
$$

Multiplicamos ambos lados por la inversa del término de la izquierda para despejar $\Delta p^r$:

$$
\Delta p^r = \left( I - A^{rr} - A^{rs} (I - A^{ss})^{-1} A^{sr} \right)^{-1} \Delta d^r
$$

Obtenemos la fórmula para calcular $\Delta p^{r}$ a partir de $\Delta d^{r}$


### Consigna 7

In [80]:
import pandas as pd

In [81]:
full_matrix = pd.read_excel('matrizlatina2011_compressed_0.xlsx', sheet_name='LAC_IOT_2011')

In [82]:
ecu_hnd_full_matrix = full_matrix[full_matrix['Country_iso3'].isin(['ECU','HND'])]

In [83]:
ecu_columns = [col for col in ecu_hnd_matrix if col.startswith('ECU')]
hnd_columns = [col for col in ecu_hnd_matrix if col.startswith('HND')]
filter_col = ['Country_iso3'] + ecu_columns + hnd_columns + ['Output']

In [84]:
ecu_hnd_matrix = ecu_hnd_full_matrix[filter_col]
ecu_hnd_matrix = ecu_hnd_matrix.replace(0,1)

Generamos el vector de total de producto producido p para cada pais, y las matrices intrarregionales e interregionales.

In [85]:
ecu_p = ecu_hnd_matrix.head(40)['Output']
hnd_p = ecu_hnd_matrix.tail(40)['Output']

In [86]:
ecu_intra_matrix = ecu_hnd_matrix.head(40)[ecu_columns]
ecu_hnd_inter_matrix = ecu_hnd_matrix.head(40)[hnd_columns]
hnd_ecu_inter_matrix = ecu_hnd_matrix.tail(40)[ecu_columns]
hnd_intra_matrix = ecu_hnd_matrix.tail(40)[hnd_columns]

Calculamos los coeficientes tecnicos de cada una de las matrices:

In [87]:
coef_tecnicos_ecu_intra = calcularCoeficientesTecnicos(ecu_intra_matrix, ecu_p)
coef_tecnicos_ecu_hnd_inter = calcularCoeficientesTecnicos(ecu_hnd_inter_matrix, ecu_p)
coef_tecnicos_hnd_ecu_inter = calcularCoeficientesTecnicos(hnd_ecu_inter_matrix, hnd_p)
coef_tecnicos_hnd_intra = calcularCoeficientesTecnicos(hnd_intra_matrix, hnd_p)

In [88]:
coef_tecnicos_ecu_intra.sample(4)

0         1         2         3         4         5         6   \
223  0.000005  0.000193  0.001883  0.006224  0.000013  0.000364  0.002229   
211  0.000096  0.000625  0.000311  0.002917  0.000426  0.000364  0.002229   
228  0.000096  0.000625  0.000070  0.002917  0.000426  0.000364  0.002229   
209  0.000096  0.000625  0.000070  0.002917  0.000426  0.000364  0.002229   

           7         8         9   ...   30            31        32        33  \
223  0.007532  0.000294  0.013815  ...  1.0  5.688231e-04  0.002279  0.000202   
211  0.000179  0.000745  0.013815  ...  1.0  4.202217e-02  0.000809  0.000019   
228  0.000179  0.000745  0.013815  ...  1.0  1.432956e-08  0.001075  0.000049   
209  0.000179  0.000745  0.013815  ...  1.0  4.202217e-02  0.001075  0.000364   

           34        35        36        37        38        39  
223  0.011135  0.000003  0.002800  0.000169  0.000408  0.000312  
211  0.000073  0.000043  0.005605  0.000361  0.000150  0.001744  
228  0.000073  0.000142  0.000298  0.000248  0.000150  0.000287  
209  0.000073  0.000142  0.000298  0.000248  0.000150  0.000027  

[4 rows x 40 columns]

Nos quedaron pendientes los últimos dos puntos